site_name: mkasianiuk
site_url: https://mkasianiuk.github.io/mkdocs/
repo_url: https://github.com/mkasianiuk/mkdocs
theme:
  name: material
  features:
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
nav:
  - ...
  - Blog:
    - blog/index.md

site_author: Maksim Kasianiuk
copyright: Maksim Kasianiuk, 2025

plugins:
  - search
  - tags
  - blog

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences